# Generated by Django 2.2 on 2020-12-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_auto_20201211_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
